apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-app-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: prometheus   # MUITO IMPORTANTE
    app.kubernetes.io/name: devops-app
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: devops-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s